### PR TITLE
CSV rather than TSV?

### PR DESCRIPTION
**Pull request by earcanal**

### CODE REVIEW

**Comment by vsoch** [comment]
And now I'm seeing this experiment is named "test-parse-url" and not "test-parse-uri" so we need to undo the PR that I just merged from you.

**Comment by vsoch** [comment]
There is no reason it needs to be csv, tsv means "tab separated value" which is better to use IMHO.

**Comment by earcanal** [comment]
So maybe remove the link, as there's no `variables.tsv` in the repo?

**Comment by vsoch** [comment]
No you are right, fixed ! https://github.com/expfactory-experiments/test-parse-url/commit/31960c44747e518516d9e79b771129fdc21f09df

**Pull request closed without merging**
